-- H2 2.1.214;
CREATE USER IF NOT EXISTS "SA" SALT '0ca1d34f7a76b9aa' HASH '3dec0531a4acb8eeae5adc132db51d2f8f36fea0b9d5000843f95d2c79cae3b6' ADMIN;
CREATE MEMORY TABLE "PUBLIC"."REGISTRATION_FORM"(

    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,

    "AGREE_TO_TERMS" BOOLEAN NOT NULL,

    "NAME" CHARACTER VARYING(255),

    "SECTORS" CHARACTER VARYING(255) ARRAY,

    "UUID" CHARACTER VARYING(255)

);
ALTER TABLE "PUBLIC"."REGISTRATION_FORM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("ID");
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.REGISTRATION_FORM;
INSERT INTO "PUBLIC"."REGISTRATION_FORM" VALUES

(1, TRUE, 'Stivler', ARRAY ['66', '69', '70', '71', '62'], '6a9d7c00-7f10-4575-8ff2-4cb85b5b3542'),

(2, TRUE, 'Jack Alltrades', ARRAY ['1', '61', '65'], '0e922909-a880-432b-91af-bd209033d6ad');
CREATE MEMORY TABLE "PUBLIC"."SECTOR"(

    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 80) NOT NULL,

    "DEPTH_LEVEL" INTEGER NOT NULL,

    "HTML_ID" INTEGER NOT NULL,

    "NAME" CHARACTER VARYING(255),

    "PARENT_ID" INTEGER

);
ALTER TABLE "PUBLIC"."SECTOR" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");
-- 79 +/- SELECT COUNT(*) FROM PUBLIC.SECTOR;
INSERT INTO "PUBLIC"."SECTOR" VALUES

(1, 0, 1, 'Manufacturing', NULL),

(2, 1, 19, 'Construction materials', 1),

(3, 1, 18, 'Electronics and Optics', 1),

(4, 1, 6, 'Food and Beverage', 1),

(5, 2, 342, 'Bakery & confectionery products', 4),

(6, 2, 43, 'Beverages', 4),

(7, 2, 42, 'Fish & fish products', 4),

(8, 2, 40, 'Meat & meat products', 4),

(9, 2, 39, 'Milk & dairy products', 4),

(10, 2, 437, 'Other', 4),

(11, 2, 378, 'Sweets & snack food', 4),

(12, 1, 13, 'Furniture', 1),

(13, 2, 389, 'Bathroom/sauna', 12),

(14, 2, 385, 'Bedroom', 12),

(15, 2, 390, U&'Children\2019s room', 12),

(16, 2, 98, 'Kitchen', 12),

(17, 2, 101, 'Living room', 12),

(18, 2, 392, 'Office', 12),

(19, 2, 394, 'Other (Furniture)', 12),

(20, 2, 341, 'Outdoor', 12),

(21, 2, 99, 'Project furniture', 12),

(22, 1, 12, 'Machinery', 1),

(23, 2, 94, 'Machinery components', 22),

(24, 2, 91, 'Machinery equipment/tools', 22),

(25, 2, 224, 'Manufacture of machinery', 22),

(26, 2, 97, 'Maritime', 22),

(27, 3, 271, 'Aluminium and steel workboats', 26),

(28, 3, 269, 'Boat/Yacht building', 26),

(29, 3, 230, 'Ship repair and conversion', 26),

(30, 2, 93, 'Metal structures', 22),

(31, 2, 508, 'Other', 22),

(32, 2, 227, 'Repair and maintenance service', 22),

(33, 1, 11, 'Metalworking', 1),

(34, 2, 67, 'Construction of metal structures', 33),

(35, 2, 263, 'Houses and buildings', 33),

(36, 2, 267, 'Metal products', 33),

(37, 2, 542, 'Metal works', 33),

(38, 3, 75, 'CNC-machining', 37),

(39, 3, 62, 'Forgings, Fasteners', 37),

(40, 3, 69, 'Gas, Plasma, Laser cutting', 37),

(41, 3, 66, 'MIG, TIG, Aluminum welding', 37),

(42, 1, 9, 'Plastic and Rubber', 1),

(43, 2, 54, 'Packaging', 42),

(44, 2, 556, 'Plastic goods', 42),

(45, 2, 559, 'Plastic processing technology', 42),

(46, 3, 55, 'Blowing', 45),

(47, 3, 57, 'Moulding', 45),

(48, 3, 53, 'Plastics welding and processing', 45),

(49, 2, 560, 'Plastic profiles', 42),

(50, 1, 5, 'Printing', 1),

(51, 2, 148, 'Advertising', 50),

(52, 2, 150, 'Book/Periodicals printing', 50),

(53, 2, 145, 'Labelling and packaging printing', 50),

(54, 1, 7, 'Textile and Clothing', 1),

(55, 2, 44, 'Clothing', 54),

(56, 2, 45, 'Textile', 54),

(57, 1, 8, 'Wood', 1),

(58, 2, 337, 'Other (Wood)', 57),

(59, 2, 51, 'Wooden building materials', 57),

(60, 2, 47, 'Wooden houses', 57),

(61, 0, 3, 'Other', NULL),

(62, 1, 37, 'Creative industries', 61),

(63, 1, 29, 'Energy technology', 61),

(64, 1, 33, 'Environment', 61),

(65, 0, 2, 'Service', NULL),

(66, 1, 25, 'Business services', 65),

(67, 1, 35, 'Engineering', 65),

(68, 1, 28, 'Information Technology and Telecommunications', 65),

(69, 2, 581, 'Data processing, Web portals, E-marketing', 68),

(70, 2, 576, 'Programming, Consultancy', 68),

(71, 2, 121, 'Software, Hardware', 68),

(72, 2, 122, 'Telecommunications', 68),

(73, 1, 22, 'Tourism', 65),

(74, 1, 141, 'Translation services', 65),

(75, 1, 21, 'Transport and Logistics', 65),

(76, 2, 111, 'Air', 75),

(77, 2, 114, 'Rail', 75),

(78, 2, 112, 'Road', 75),

(79, 2, 113, 'Water', 75);
ALTER TABLE "PUBLIC"."SECTOR" ADD CONSTRAINT "PUBLIC"."FKN6JFOE213MLNAFOAIAOLVH5C8" FOREIGN KEY("PARENT_ID") REFERENCES "PUBLIC"."SECTOR"("ID") NOCHECK;
